"""Calibration anchors: the band-offset fit round-trips through the
package's own heterostructure solver (the forward model IS the public
code path); its error bar matches a finite-difference re-fit; the
sheet-density inversion is the exact closed-form inverse of
`depolarization_shift` (round trip to machine-level precision, exact
linearity in n_s, exact derivative for the error bar); and both tools
refuse -- with the physical reason -- measurements no parameter value
can reproduce."""
import numpy as np
import pytest

from kpenvelope import (aln_rinke2008, depolarization_shift,
                        fit_band_offset, gan_rinke2008, layered_profile,
                        offset_sensitivity, sheet_density_from_shift,
                        solve_heterostructure)

GAN = gan_rinke2008()
ALN = aln_rinke2008()
Z = np.linspace(0.0, 12.0, 97)
LAYERS = [(4.0, ALN, 1.0), (4.0, GAN, 0.0), (4.0, ALN, 1.0)]
PARAMS_LIST, UNIT = layered_profile(Z, LAYERS)
OFFSET_TRUE = 0.5


def _spacing(offset, states=(0, 2)):
    e, _ = solve_heterostructure(Z, PARAMS_LIST,
                                 band_edge=offset * UNIT,
                                 n_states=max(states) + 1)
    return abs(float(e[states[0]]) - float(e[states[1]]))


def test_offset_round_trip_and_sigma():
    """Synthetic measurement generated by the public solver at a known
    offset: the fit must recover that offset, and its error bar must
    match perturbing the measurement by one sigma and re-fitting."""
    e_meas = _spacing(OFFSET_TRUE)
    sens = offset_sensitivity(Z, PARAMS_LIST, UNIT, OFFSET_TRUE)
    assert abs(sens) > 1e-4          # the measurement does feel the offset
    fit = fit_band_offset(Z, PARAMS_LIST, UNIT, e_meas,
                          bracket=(0.4, 1.5), sigma_e_ev=1e-5)
    assert abs(fit["offset_ev"] - OFFSET_TRUE) < 1e-6
    assert abs(fit["e_model_ev"] - e_meas) < 1e-9
    # delta-method error bar vs an actual re-fit at e_meas + sigma
    fit2 = fit_band_offset(Z, PARAMS_LIST, UNIT, e_meas + 1e-5,
                           bracket=(0.4, 1.5))
    shift = abs(fit2["offset_ev"] - fit["offset_ev"])
    assert np.isclose(shift, fit["sigma_offset_ev"], rtol=0.05)


def test_offset_bracket_refusal_names_both_ends():
    e_meas = _spacing(OFFSET_TRUE)
    with pytest.raises(ValueError, match="does not straddle"):
        fit_band_offset(Z, PARAMS_LIST, UNIT, e_meas,
                        bracket=(0.9, 1.5))
    # states (0, 1) are an exactly degenerate Kramers pair at k = 0:
    # no spacing to fit, refused downstream by the exact degeneracy
    assert abs(_spacing(OFFSET_TRUE, states=(0, 1))) < 1e-12


def test_sheet_density_exact_round_trip_and_linearity():
    """Forward with a known density through the package's own
    `depolarization_shift`, invert, recover -- and the relation is
    exactly linear in n_s, so doubling the density exactly doubles
    alpha."""
    e, env = solve_heterostructure(Z, PARAMS_LIST,
                                   band_edge=OFFSET_TRUE * UNIT,
                                   n_states=6)
    ns_true = 0.05                                  # nm^-2
    fwd = depolarization_shift(Z, env[0], env[5], e[0], e[5],
                               n_sheet=ns_true, eps_r=GAN.eps_r)
    inv = sheet_density_from_shift(Z, env[0], env[5], e[0], e[5],
                                   fwd["E_shifted"], GAN.eps_r,
                                   sigma_e_ev=1e-4)
    assert abs(inv["n_sheet"] - ns_true) < 1e-10 * ns_true
    assert abs(inv["e_bare"] - fwd["E_bare"]) < 1e-12
    assert abs(inv["alpha"] - fwd["alpha"]) < 1e-10 * fwd["alpha"]
    fwd2 = depolarization_shift(Z, env[0], env[5], e[0], e[5],
                                n_sheet=2.0 * ns_true, eps_r=GAN.eps_r)
    assert abs(fwd2["alpha"] - 2.0 * fwd["alpha"]) \
        < 1e-12 * fwd2["alpha"]
    # exact derivative for the error bar, checked by finite difference
    d = 1e-6
    inv_p = sheet_density_from_shift(Z, env[0], env[5], e[0], e[5],
                                     fwd["E_shifted"] + d, GAN.eps_r)
    fd = (inv_p["n_sheet"] - inv["n_sheet"]) / d * 1e-4
    assert np.isclose(inv["sigma_n_sheet"], fd, rtol=1e-3)


def test_sheet_density_below_bare_refused():
    e, env = solve_heterostructure(Z, PARAMS_LIST,
                                   band_edge=OFFSET_TRUE * UNIT,
                                   n_states=6)
    bare = abs(float(e[0]) - float(e[5]))
    with pytest.raises(ValueError, match="pushes the resonance up"):
        sheet_density_from_shift(Z, env[0], env[5], e[0], e[5],
                                 0.99 * bare, GAN.eps_r)


def test_input_refusals():
    e, env = solve_heterostructure(Z, PARAMS_LIST,
                                   band_edge=OFFSET_TRUE * UNIT,
                                   n_states=3)
    with pytest.raises(ValueError, match="band_edge_unit"):
        fit_band_offset(Z, PARAMS_LIST, UNIT[:-1], 0.1, (0.1, 1.0))
    with pytest.raises(ValueError, match="not all"):
        fit_band_offset(Z, PARAMS_LIST, 0.0 * UNIT, 0.1, (0.1, 1.0))
    with pytest.raises(ValueError, match="bracket"):
        fit_band_offset(Z, PARAMS_LIST, UNIT, 0.1, (1.0, 0.1))
    with pytest.raises(ValueError, match="distinct"):
        fit_band_offset(Z, PARAMS_LIST, UNIT, 0.1, (0.1, 1.0),
                        states=(1, 1))
    with pytest.raises(ValueError, match="positive"):
        sheet_density_from_shift(Z, env[0], env[2], e[0], e[2], -0.1,
                                 GAN.eps_r)
